# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "wh-capmon-newrelic-eu-west-1-tfstate"
    dynamodb_table = "wh-capmon-newrelic-alerting-tflock"
    key            = "dev/alerts/terraform.tfstate"
    region         = "eu-west-1"
  }
}
