# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "newrelic" {
  api_key = var.newrelic_personal_api_key
  admin_api_key = var.newrelic_api_key
  account_id = var.newrelic_account_id
  region = var.newrelic_region
  version = "2.12.1"
}
